[package]
name = "ai-asset-generator"
version = "0.2.0"
edition = "2021"

[dependencies]
ai-images = { git = "ssh://github.com/DrakeRichards/ai-images.git", version = "0.1.1" }
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
llm-structured-response = { git = "ssh://github.com/DrakeRichards/llm-structured-response.git", version = "0.1.2" }
minijinja = { version = "2.5.0", features = ["serde_json"] }
random-phrase-generator = { git = "ssh://github.com/DrakeRichards/random-phrase-generator.git", version = "0.1.0" }
serde = "1.0.216"
serde_json = "1.0.134"
tokio = { version = "1.42.0", features = ["rt-multi-thread"] }
toml = "0.8.19"

[build-dependencies]
