[package]
name = "random_phrase_generator"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
csv = { workspace = true }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
ex = { workspace = true }

[lints]
workspace = true
