[package]
name = "random_phrase_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
csv = "1.3.1"
rand = "0.8.5"
serde = "1.0.216"

[build-dependencies]

[dev-dependencies]
