[package]
name = "random_phrase_generator"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
csv = "1.3.1"
rand = "0.8.5"
serde = { workspace = true, features = ["derive"] }
ex = { workspace = true }

[lints]
workspace = true
