[package]
name = "llm_structured_response"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
async-openai = "0.26.0"
async-trait = "0.1.84"
clap = { version = "4.5.23", features = ["derive"] }
dotenvy = "0.15.7"
serde = "1.0.216"
serde_json = "1.0.134"

[build-dependencies]

[dev-dependencies]
tokio = { version = "1.42.0", features = ["rt-multi-thread"] }
